title: Pinar Gibson
description: |
  I am a junior data analyst with a strong background in broadcast media. I thrive on extracting insights from complex datasets. My meticulous approach to problem-solving and keen eye for detail ensure precision and efficiency throughout the analytics workflow. Known for my collaborative spirit, I foster a culture of teamwork and actively share my knowledge. I am passionate about leveraging my unique blend of analytical skills and media industry experience to drive data-driven decision-making across diverse sectors. [LinkedIn](https://www.linkedin.com/in/pinar-gibson/)

google_analytics:
theme: jekyll-theme-minimal