title: Pinar Gibson
description: |
  <p>I am a junior data analyst with a strong background in broadcast media. I thrive on extracting insights from complex datasets. My meticulous approach to problem-solving and keen eye for detail ensure precision and efficiency throughout the analytics workflow. Known for my collaborative spirit, I foster a culture of teamwork and actively share my knowledge. I am passionate about leveraging my unique blend of analytical skills and media industry experience to drive data-driven decision-making across diverse sectors.</p>
  
  <p><b>SKILLS</b>
  <ul>
  <li>Analytics: Data Extraction, Cleaning and Wrangling, Data Modelling, Data Analysis and Interpretation, Visualisation, Dashboard Design, Presentation</li>
  <li>Tools and Languages: Microsoft Excel, Power BI, Power Query, Tableau, SQLite, PostgreSQL, Python, Pandas, Matplotlib, Plotly, Seaborn, Scikit-Learn, Beautifulsoup, Requests, Jupyter Notebooks</li>
  <li>Non-Technical: Strategic Planning, Effective Time Management, Methodical Approach, Problem Solving, Multi-Tasking, Attention to Detail and Accuracy, Proactivity</li>
  </ul>
  <p><a href="https://www.linkedin.com/in/pinar-gibson/">View My LinkedIn Profile</a></p>

google_analytics:
theme: jekyll-theme-minimal